[package]
title = "omni.ui Julia Quaternion Modeler Example"
description = "A window example with custom UI elements"
version = "1.0.1"
category = "Example"
authors = ["Alan Cheney"]
repository = "https://gitlab-master.nvidia.com/omniverse/kit-extensions/kit-windows"
keywords = ["example", "window", "ui", "julia_modeler"]
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"omni.ui" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.popup_dialog" = {}

[[python.module]]
name = "omni.example.ui_julia_modeler"

[[test]]
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]
dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
]
